### PR TITLE
Ebooks pr

### PR DESCRIPTION
**Pull request by phanirithvij**

### CODE REVIEW

**Comment by phanirithvij** [comment]
wait what, does this really ping everyone?

If so I'm sorry everyone. @stjepanjurekovic please delete this issue.

**Comment by stjepanjurekovic** [comment]
Is this ok now?

**Comment by phanirithvij** [comment]
I think it didn't mention all of them. You can merge it

**Comment by phanirithvij** [comment]
Wait, too many errors. I'll push it here.

**Pull request merged**
